name: Running tests

permissions: read-all

on:
  workflow_call:
    inputs:
      node_env:
        required: true
        type: string

  pull_request:
    branches:
      - main
    paths:
      - '**.js*'
      - '**.ts*'
      - package*.json
      - .github/workflows/ci-tests.yml

  push:
    branches:
      - main
    paths:
      - '**.js*'
      - '**.ts*'
      - package*.json
      - .github/workflows/ci-tests.yml

env:
  NODE_ENV: ${{ inputs.node_env }}
  NEXT_TELEMETRY_DISABLED: 1
  # we build a dev binary for use in CI so skip downloading
  # canary next-swc binaries in the monorepo
  NEXT_SKIP_NATIVE_POSTINSTALL: 1
  CI: true

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set.outputs.version }}
    steps:
      - name: Setting API Version
        id: set
        run: echo "::set-output name=version::${{ vars.NODE_ENV }}"

  test:
    name: Test with Node.js ${{ matrix.node }}
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false
        matrix:
          node: [lts/*, latest]

    steps:
      - name: Cheking out the code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ matrix.node }}

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Running tests
        run: yarn test